# Increase the buggers for stunnel.
#
# ENT-817 related
#
# Place this file in /etc/stunnel with the name "00-buffers.conf" and restart the stunnel service. Will need to be set on each node.
#
#

socket = a:SO_RCVBUF=4194304
socket = a:SO_SNDBUF=4194304
socket = l:SO_RCVBUF=4194304
socket = l:SO_SNDBUF=4194304
socket = r:SO_RCVBUF=4194304
socket = r:SO_SNDBUF=4194304
